### ISSUE TITLE
Banner Kings Issue with Banner Craft

### ISSUE THREAD

**Issue by mooneyclan** [6135/Bannerlord.BannerCraft#18]
**Describe the bug**
problem with loading craftable items and weapons. This may be a compatibility issue with one of Banner King dependency

**Versions and Mods**
Version of the game: 1.2.8
Version of the mod: v1.0.29
Version of the Dependencies: 
BannerCraftRBMPatch 1.0.1
List of all installed mods and their versions:
https://report.butr.link/E8F397
This crash report will provide all my mods, version and load order excluding the RBM Patch which I thought might fix my issue.  This crash is unrelated to your mod.

**To Reproduce**
Go to Smithy screen.  Two of your Craft bars are present.  It doesn't load properly

**Expected behavior**
Self evident.  You created it.  I use it.  It not loading.

**Screenshots**
![image](https://github.com/6135/Bannerlord.BannerCraft/assets/24855472/4a4dadde-4887-4249-9ce1-253a1d9426e6)

**Comment by mooneyclan** [comment]
The screenshot is from your nexus mod bug report page on Banner Craft

**Comment by mooneyclan** [comment]
Banner Kings implements its own crafting system under a tab also called Craft.  Is there a way to gut the BK Craft menu & code?  BK Craft menu is unusable I just found out.  It is literally just one massive list of all items.  Thousands of them

**Comment by mooneyclan** [comment]
![image](https://github.com/6135/Bannerlord.BannerCraft/assets/24855472/7508e9bd-df7e-4dbe-885c-732b5f17f4dd)

**Comment by mooneyclan** [comment]
![image](https://github.com/6135/Bannerlord.BannerCraft/assets/24855472/9f6e718a-09e9-4ba4-aff7-2b980903ce04)

**Comment by mooneyclan** [comment]
To basically remove the conflict I removed the two instances of Crafting folder within Banner Kings.  Once I did that Banner Craft loads properly in the smithy and works.  

Order without power has instructed me how to properly fix it but never done a mod before.

**Comment by OrderWOPower** [comment]
Added compatibility with BK in 1.1.0.
