### ISSUE TITLE
Cant craft weapons

### ISSUE THREAD

**Issue by 6135** [6135/Bannerlord.BannerCraft#7]
Cant craft weapons, when i choose the weapon to forge it keeps crafting crowns))
russian version of the game if it matters
have Better smithing Continued

**Comment by 6135** [comment]
The language version should not matter. It might be an incompatibility with BSC. Can you tell me which version of the game and which version of the mod you're using so I can look further into it?

I've created an issue on [GitHub](https://github.com/6135/Bannerlord.BannerCraft/issues/7). It is easier for me to keep track of it there.

**Comment by alegwar** [comment]
Better smithing continued v 1.1.0.8
Game ver v 1.1.6
Bannercraft v 1.0.21.0
also
have Unlimited smithing v 1.0.2 but it should not matter

**Comment by 6135** [comment]
@alegwar looking into it.

**Comment by 6135** [comment]
@alegwar Should be fixed in the next release in a couple of minutes. Please test it out if you can.

**Comment by alegwar** [comment]
@6135 Checked this right now, issue is fixed, thanks

**Comment by 6135** [comment]
Good! Will close the issue, if you need to reopen it, refer to this one please.
